### ISSUE TITLE
Invalid response from OpenAI API

### ISSUE THREAD

**Issue by ikhyunAn** [CS-3300-P8/RecipeBuilder#11]
# Problem
Invalid response from OpenAI API may be causing these issues

Search failed: Error: Invalid response from API
    at handleSearch (IngredientSearchPage.jsx:37:15)

Error generating recipe: Error: Failed to generate recipe
    at generateRecipe (RecipeGeneratorPage.jsx:52:15)

These can be observed when testing the application on the following features:
- Ingredient Search
- Recipe Generate

Both of these features require OpenAI API call.

# Possible reasons
- Invalid API key
- mapping wrong data structures
- wrong key

# Updates (commits) that have been made so far on this branch

1. Created `openaiFactory.js` to create Factory Pattern, which will be used when making calls to OpenAI
2. created prompt for recipe genration
3. moved normalizedsearch feature from `index.js` to `openaiFactory.js`

**Comment by ikhyunAn** [comment]
![image](https://github.com/user-attachments/assets/cb8b62c7-ed13-469f-a3f3-9185ad650e99)

**Comment by ikhyunAn** [comment]
# Issue Found
`JSON.parse` was called twice

# Solution
removed one parse

# Result
Ingredient Search is working

# Remaining Problem
Recipe generator still not working

**Comment by ikhyunAn** [comment]
# Fix to Recipe Generator
Updated JSON parser, stringifier, etc.

# Result
Recipe generator now works but with occasional failures
